### ISSUE TITLE
prince-CLL: formatting issues. Chapter 0 + Instruction!

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#104]
Okay, here are formatting issues. No issues related to the languages please.

Read this and open issues http://vrici.lojban.org/~rlpowell/media/public/cll_build/cll_prince.pdf
## Preface
- Second Edition <-- center please or just type "Version 1.1, 2015" or whatever
- < gleki> page 10 is useless
  *\* <rlpowell> page 10 is so that the chapter starts on the right hand page.

**Comment by rlpowell** [comment]
- Version 1.1, Generated 2015-09-28 (using the VERSION) file I just added
- I really wish you wouldn't use page numbers in your reports; I have no idea what you mean by page 10 or what was wrong with it
