### ISSUE TITLE
prince-CLL: formatting issues. Chapter 1

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#105]
## Chapter 1
- open literature in the article ““Loglan”” <-- why double quotes?
- page 11 doesnt display its number.  intentional?
- Page 12. "Lojban is designed to be used by people in communication with each other, and
  possibly in the future with computers" <-- needs a marked list

**Comment by rlpowell** [comment]
- fixed
- assuming you mean the chapter start page: I think usually chapter pages don't have numbers?, but I'm putting them back anyway
- fixed
