### ISSUE TITLE
Looking thru the TODO file ...

### ISSUE THREAD

**Issue by FrankDMartinez** [lojban/cll#14]
The file says:

```
2. Example 2.9 could do with some re-formatting (compare 5.3 in http://dag.github.com/cll/2/5/ )
```

While I can find 5.3 easily enough, which part is `Example 2.9`?

**Comment by rlpowell** [comment]
On Thu, Jun 21, 2012 at 10:49:07AM -0700, xuinkrbin wrote:

> The file says:
> 
> ```
> 2. Example 2.9 could do with some re-formatting (compare 5.3 in http://dag.github.com/cll/2/5/ )
> ```
> 
> While I can find 5.3 easily enough, which part is `Example 2.9`?

The one that has the same content as 5.3 in that link.

-Robin

**Comment by rlpowell** [comment]
On Thu, Jun 21, 2012 at 10:49:07AM -0700, xuinkrbin wrote:

> The file says:
> 
> ```
> 2. Example 2.9 could do with some re-formatting (compare 5.3
> in http://dag.github.com/cll/2/5/ )
> ```
> 
> While I can find 5.3 easily enough, which part is `Example 2.9`?

If you're planning on doing work out of the TODO, do you have an
account on vrici so you can build the PDF?  The toolchain is quite
huge at this point, and hard to set up.

If not, you should come find me on IRC.

-Robin

**Comment by FrankDMartinez** [comment]
Thanks. I do not have such an acount at this point in time. I will find You on IRC as soon as I can arrange it.

**Comment by FrankDMartinez** [comment]
Should I get the account first and then find You?

**Comment by rlpowell** [comment]
On Thu, Jun 21, 2012 at 11:17:38AM -0700, xuinkrbin wrote:

> Should I get the account first and then find You?

Umm, I'm talking about an ssh login to one of my servers, the one
that is set up for CLLv1.1 builds.  How would you get that without
talking to me?  :D

-Robin

**Comment by FrankDMartinez** [comment]
Good point. See You on IRC ...
