### ISSUE TITLE
Th ligatures mangled throughout (Win 8.1)

### ISSUE THREAD

**Issue by ErikNatanael** [lojban/cll#148]
![cll th ligature problem](https://cloud.githubusercontent.com/assets/12977989/8267278/4ca65abe-175a-11e5-98ef-f54deda0ae86.png)

As you can see in the picture, every time an uppercase T is followed by a lowercase h they are mangled into obscurity. It might be something on my specific system, but this shouldn't happen regardless of system. This doesn't happen with other PDFs.

**Comment by rlpowell** [comment]
This _definitely_ doesn't happen for me.  Can you confirm that it's happening with http://vrici.lojban.org/~rlpowell/media/public/cll_build-2015-06-20/cll_prince.pdf ?  Can you try another PDF reader on the same system?

**Comment by ErikNatanael** [comment]
It happened with that file in Adobe Reader (latest version), but then I installed Foxit Reader which showed it fine and now it looks as it should in Adobe Reader as well. There must have been some systemwide issue (fonts?) that was fixed by the Foxit installation program. Anyway, if no one else is experiencing the problem I suggest we close the issue.

**Comment by solpahi** [comment]
Nathnainiel:

> It happened with that file in Adobe Reader (latest version), but then I
> installed Foxit Reader which showed it fine and now it looks as it
> should in Adobe Reader as well. There must have been some systemwide
> issue (fonts?) that was fixed by the Foxit installation program. Anyway,
> if no one else is experiencing the problem I suggest we close the issue.

I've definitely seen this happen on my computer, too. (WinXP + Adobe Reader)

**Comment by solpahi** [comment]
Actually I just realized that this apparently only happens in my Firefox (which uses Adobe Acrobat) but not when I view the file locally.

**Comment by rlpowell** [comment]
Can you see if
http://vrici.lojban.org/~rlpowell/media/public/cll_prince_spacing_test_2015-07-20.pdf
fixes it?

On Mon, Jul 20, 2015 at 04:38:58AM -0700, selpahi wrote:

> Actually I just realized that this apparently only happens in my Firefox (which uses Adobe Acrobat) but not when I view the file locally.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lojban/cll/issues/148#issuecomment-122857681

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i dafsku lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u

**Comment by solpahi** [comment]
rlpowell:

> Can you see if
> http://vrici.lojban.org/~rlpowell/media/public/cll_prince_spacing_test_2015-07-20.pdf
> fixes it?

It seems so! Looks normal in my browser now.

(I compared with 
http://vrici.lojban.org/~rlpowell/media/public/cll_build-2015-06-20/cll_prince.pdf 
  where the problem does appear)

**Comment by rlpowell** [comment]
On Mon, Jul 20, 2015 at 09:49:17AM -0700, selpahi wrote:

> rlpowell:
> 
> > Can you see if
> > http://vrici.lojban.org/~rlpowell/media/public/cll_prince_spacing_test_2015-07-20.pdf
> > fixes it?
> 
> It seems so! Looks normal in my browser now.
> 
> (I compared with 
> http://vrici.lojban.org/~rlpowell/media/public/cll_build-2015-06-20/cll_prince.pdf 
>   where the problem does appear)

Excellent.  I can confirm that it was broken in the latter for me in
PDF.js/FF, too, and fine in the former, so I think we're good.

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i dafsku lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u
