### ISSUE TITLE
Examples: enable autowidth and cell borders, decrease spacing between cells

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#155]
http://vrici.lojban.org/~rlpowell/media/public/cll_prince_spacing_test_2015-08-12-full.pdf

Example 6.57
I suggest 
1. decreasing spacing so that "the-set-of" fits into one line
2. show cell borders using style="border: 1px solid #aaa;" (or try other colors like #999, ... #eee etc.)
3. also autowidth of table columns would be nice if it isn't yet enabled
4. Also if cell border are enabled then "..." for empty cells can be deleted or made "color: white" so that we stop seeing them. "-" can also be considered an empty cell.

**Comment by rlpowell** [comment]
We did all of these things; see http://vrici.lojban.org/~rlpowell/media/public/cll_prince_2015-09-17.pdf
