### ISSUE TITLE
"Quantificational pro-sumti ( da, de, di) "

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#156]
After example 6.81 
"Quantificational pro-sumti ( da, de, di)" <-- add a space after "di"

Same for other usage of brackets on that page. Seems to be a global problem.

**Comment by rlpowell** [comment]
So two things:
1.  I disagree, I think it should be (da, de, di)
2.  This cannot reasonably be fixed programmatically; someone needs to actually go modify the source in the relevant places.

**Comment by janek37** [comment]
You can search them with something like

```
$ grep '([ ]*$' -rn .
```

(on Unix-like systems). This currently gives 137 results.

**Comment by rlpowell** [comment]
_Hmm_.

Given that, we actually probably _could_ do it programmatically;
I'll take a look.

On Mon, Aug 31, 2015 at 01:33:03PM -0700, janek37 wrote:

> You can search them with something like
> 
> ```
> $ grep '([ ]*$' -rn .
> ```
> 
> (on Unix-like systems). This currently gives 137 results.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lojban/cll/issues/156#issuecomment-136490876

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i dafsku lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u

**Comment by rlpowell** [comment]
http://vrici.lojban.org/~rlpowell/media/public/cll_prince_2015-08-31-2.pdf
-- better?

On Mon, Aug 31, 2015 at 01:33:03PM -0700, janek37 wrote:

> You can search them with something like
> 
> ```
> $ grep '([ ]*$' -rn .
> ```
> 
> (on Unix-like systems). This currently gives 137 results.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lojban/cll/issues/156#issuecomment-136490876

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i dafsku lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u
