### ISSUE TITLE
Make rules for formatting: Lojban examples, English translations, English interlinear glosses.

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#159]
Let's use http://vrici.lojban.org/~rlpowell/media/public/cll_prince_2015-08-31.pdf as the reference.

Example 2.18
Lojban: italic, emphasis: bold
Glossing: bold
English: normal roman

Within English text Lojban text is usually italic.

This indeed looks like there is some formalization. Any other ideas?

**Comment by lagleki** [comment]
Table 9.3 doesn't follow the convention above.

**Comment by lagleki** [comment]
This convention makes English glossing wide and thus taking a lot of space. Consider changing to Lojban is bold, Glossing is italic or normal.

**Comment by rlpowell** [comment]
This is what we're doing; if there's a further action item here I don't see it.

**Comment by lagleki** [comment]
mostly any Lojban text should be wrapped in a certain tag and a single css style is to be applied to this text throughout the whole CLL.

**Comment by rlpowell** [comment]
To the best of my knowledge this is, in fact, the case, except for in the section-start tables where it seemed like italics would just be kind of silly (since it's obvious what's Lojban in that case).

**Comment by lagleki** [comment]
2015-09-28 11:11 GMT+03:00 rlpowell notifications@github.com:

> To the best of my knowledge this is, in fact, the case

depends. E.g. section 1.11 starts with
The following cmavo are discussed in this section:
ce'u KOhA abstraction focus

and ce'u isn't in italic.

, except for in the section-start tables where it seemed like italics would

**Comment by rlpowell** [comment]
Yes, that's exactly what I said; re-read my comment, please.  If you feel that such tables should _also_ be italicized, say so and why.
