### ISSUE TITLE
autoinsert a space after apostrophe.

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#178]
"When assembling rafsi together into lujvo, the rules for valid brivla must be followed: a consonant
cluster must occur in the first five letters (excluding y and ')"

This "    ')    " does look nice. Consider autoadding some space (e.g. margin-right via CSS) for Lojban words ending in "   '   "

**Comment by rlpowell** [comment]
I don't think that's actually feasible in CSS; I did it by hand, as there were very few cases.
