### ISSUE TITLE
lojban-to-english dictionary doesn't include apostrophe in definitions

### ISSUE THREAD

**Issue by lagleki** [lojban/cll#187]
in English definitions of Lojban words in the appendix ' is not displayed. i.e. du'u is turned into duu.

Also pls update the dictionary from jbovlaste.

**Comment by rlpowell** [comment]
I'm sorry, I don't know what you're talking about?

dubjavme'a
x1 is less than or equal to x2
du'e
digit/number: too many; subjective.
du'i
dunli modal, 1st place (equalled by) equally; as
much as ...
du'u
abstractor: predication/bridi abstractor; x1 is
predication [bridi] expressed in sentence x2.

^^ that's from http://vrici.lojban.org/~rlpowell/media/public/cll_prince_2015-10-11.pdf

**Comment by lagleki** [comment]
I'm talking about English definitions. E.g. this is the definition of
bangu = x1 is a/the language/dialect used by x2 to express/communicate x3 (sio/duu, not quote).

See that sio/duu?

**Comment by rlpowell** [comment]
Got it. I'll take a look.

As to the other: it pulls from jbovlaste on every run, using http://jbovlaste.lojban.org/export/xml-export.html?lang=en

**Comment by rlpowell** [comment]
This was an amazing catch!  There turned out to be a _bunch_ of things that were getting stripped, like all ellipses.  Thank you so much!
