### ISSUE TITLE
C2. S5. Example "Talking is going on..." could do with some re-formatting

### ISSUE THREAD

**Issue by ento** [lojban/cll#23]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L31)

```
Example 2.9. 
Talking is going on, with speaker John and listener Sam and subject matter engineering and language Lojban.
```

Compare with the equivalent example in http://dag.github.com/cll/2/5/

```
5.3)   Talking is going on,
           with speaker John
           and listener Sam
           and subject matter engineering
           and language Lojban.
```

pdf: needs fix
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: needs fix
mobi: needs fix

**Comment by rlpowell** [comment]
I disagree that is important to go to a bunch of trouble to preserve this particular case's idiosyncratic indentation.
