### ISSUE TITLE
Updating the web version of CLL.

### ISSUE THREAD

**Issue by audreytoskin** [lojban/cll#239]
I see that the `gh-pages` branch has not been updated since June 2014. Is there a reason we haven't merged any of the changes since then? This is, I believe, the branch which tracks the live website at lojban.github.io/cll, right?

I ask because I'd like to make a pull request updating the CSS for the web version of CLL -- e.g., making shorter horizontal line lengths, so the chapters are easier to read. But I want readers to able to actually see the changes, so I'm not sure if I should base my edits on the `gh-pages` branch, or `docbook-prince`.

**Comment by lagleki** [comment]
this branch has to be automatically generated from prince. That's the only
requirement.

2016-01-06 8:38 GMT+03:00 Andrew Toskin notifications@github.com:

**Comment by audreytoskin** [comment]
...Okay, so I'm much more familiar with plain HTML than I am with DocBook/XML. None of my changes to `cll/scripts/master.css` are showing up in the output stylesheet `cll/build/xhtml_chapters/final.css`. And none of the `.xsl` files seemed relevant, when I glanced through those.

I'm only making edits in the `@media screen {}` styles block in `master.css`. I'm recompiling the book using

``` bash
./cll_build -t -T xhtml_chapters
```

and I clean out the `build/` directory before recompiling. Packages that I've made sure to install (on my Fedora system):
- docbook5-style-xsl
- libxslt (which provides xsltproc)
- xmlto
- ruby, ruby-devel, and rubygems
  - I also ran `gem install bundler` and `bundle install`
- calibre (which provides ebook-convert)

Any hints?

**Comment by audreytoskin** [comment]
bump.

Anyone?

**Comment by lagleki** [comment]
Well, you may try contacting rlpowell on IRC. He is
https://github.com/rlpowell as well.

2016-01-15 8:32 GMT+03:00 Andrew Toskin notifications@github.com:

**Comment by rlpowell** [comment]
You shouldn't need any special knowledge; it's normal CSS affecting normal HTML.  See  http://vrici.lojban.org/~rlpowell/media/public/cll_build-2015-06-20/cll-xhtml-sections/
 for example.

I suggest, as I always do, that you come get an account on my server, because there I know for sure that the toolchain works, instead of spending days trying to get it working on your system.

WRT this specifically: "None of my changes to cll/scripts/master.css are showing up in the output stylesheet cll/build/xhtml_chapters/final.css." -- I have no idea whatsoever how that could be possible in the docbook-prince branch ; ./scripts/master.css is definitely the source for the CSS, changes there should _definitely_ be reflected in ./build/xhtml_chapters/final.css after you run ./cll_build -T xhtml_chapters ; I don't even know where to start in debugging such a problem, but the output of something like:  ./cll_build -T xhtml_chapters_web -t chapters/03.xml
would be a good start.

**Comment by audreytoskin** [comment]
The command `./cll_build -T xhtml_chapters_web -t chapters/03.xml` does seem to work. So maybe the `_web` at the end of the target is what was needed?

One more question: What file would I edit to add a `<meta>` tag to the `<head>` of each HTML document?

Setting the initial scale of the viewport to 1 is almost always the best option for properly responsive pages on a mobile device (and making the site more "responsive" is one of my goals). However most mobile browsers don't have this set by default, opting instead to try to scale down a desktop-sized web page. We need to add this:

`<meta name="viewport" content="width=device-width, initial-scale=1" />`

**Comment by rlpowell** [comment]
On Tue, Jan 19, 2016 at 11:14:14PM -0800, Andrew Toskin wrote:

> The command `./cll_build -T xhtml_chapters_web -t chapters/03.xml`
> does seem to work. So maybe the `_web` at the end of the target is
> what was needed?

That really shouldn't be the case, but I suppose it's possible.

> One more question: What file would I edit to add a `<meta>` tag to
> the `<head>` of each HTML document?

xml/docbook2html_config_not-prince.xsl

> Setting the initial scale of the viewport to 1 is almost always
> the best option for properly responsive pages on a mobile device
> (and making the site more "responsive" is one of my goals).
> However most mobile browsers don't have this set by default,
> opting instead to try to scale down a desktop-sized web page. We
> need to add this:
> 
> `<meta name="viewport" content="width=device-width, initial-scale=1" />`

I just pushed this change for you; please test it.

**Comment by audreytoskin** [comment]
Looks good, thanks.

**Comment by audreytoskin** [comment]
Specifying the language in a tag attribute is required for automatic hyphenation, which helps to avoid strange word spacing in fully justified text, and helps screen readers correctly identify the language of the text content. In XHTML 1.0, we should add both the XML and HTML versions of the lang attribute ( `xml:lang="en" lang="en"` ) to the `<html>` element.

However, if we ever switched to XHTML 1.1, we could use just the XML version, or just the HTML attribute for HTML5.

**Comment by rlpowell** [comment]
Done; please test.

**Comment by audreytoskin** [comment]
Very good, thanks.

**Comment by audreytoskin** [comment]
I have another point I'd like to talk about, but it's a little more complicated, and would require a more complicated solution. I'll think on it, and then probably post my suggestion in another issue.

For now, I've mostly been worrying about the CSS. I think I'm ready to submit my pull request. Thanks for helping with the XML, and sorry it's taken me so long to get this done.
