### ISSUE TITLE
References to multiple examples broken. Need way to refer to an example with less boilerplate text

### ISSUE THREAD

**Issue by mezohe** [lojban/cll#248]
101001000100001 [reports](http://reddit.com/4mpbkq):

> I found a mistake on page 291 I think. "In a real-life situation, Examples 3.1-3.7 would" should be referring to examples 13.25-13.31. Don't know who to tell.

This seems to be a larger issue, actually. Searching through the book for "Examples " shows that a good amount of references to multiple examples are broken: they either have out-of-date example numbers, or they are full of auto-generated vebosity.

> Examples Example 5.26, Example 5.27, Example 5.28, Example 5.29, and Example 5.36 are repeated here as Examples Example 5.132, Example 5.140, Example 5.148, Example 5.156, and Example 5.164 respectively

To fix these properly we would need a way to link to examples that doesn't result in "Example " prepended or page numbers appended.

**Comment by mezohe** [comment]
Missing references added in 103da8f; this results in slightly more awkward phrasing for now

**Comment by rlpowell** [comment]
Nice catch!
