### ISSUE TITLE
Misaligned gloss in second-to-last example of section 18.5

### ISSUE THREAD

**Issue by maltys** [lojban/cll#250]
In the example mentioned in the title there is no gloss for bi'e, but the "-" to skip that entry is missing in the code, so that the following glosses are in the wrong place. (This is relevant at least in the pdf version, but can't be observed in the html version).
I opened a pull request containing the two-character fix, see below.

**Comment by lagleki** [comment]
Not vetoed according to https://mw.lojban.org/papri/CLL_1.2._Technical hence is allowed to be preset in docbook-prince branch.
