### ISSUE TITLE
C4. S15. Broken HTML character codes around "Hellas"

### ISSUE THREAD

**Issue by ento** [lojban/cll#28]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L36)

```
&#x201C;Hellas&#x201D;)
```

This is from the <quote xml:lang="el"/> tag not being handled properly in the docbook->html conversion.

All formats are affected.

**Comment by rlpowell** [comment]
Currently:

xelso
Greek (from «Hellas»)

in the PDF.
