### ISSUE TITLE
C5. S14. Table of language acronyms could use reformatting to save space

### ISSUE THREAD

**Issue by ento** [lojban/cll#29]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L38)

Currently, the HTML markup is 

``` html
<div class="variablelist">
  <dl>
    <dt>Language acronym</dt>
    <dd>Language name</dd>
  </dl>
</div>
```

pdf: looks okay-ish (already formatted in two columns)
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: needs fix
mobi: needs fix

**Comment by rlpowell** [comment]
Had trouble finding this, so for the record: these are abbreviations, not acronyms, and the section is     <title>Some types of asymmetrical tanru</title>

**Comment by rlpowell** [comment]
Now 3-column in pdf and html; haven't checked the other two.
