### ISSUE TITLE
C7. Example 7.39 is hella ugly.  Like, seriously

### ISSUE THREAD

**Issue by ento** [lojban/cll#31]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L41)

jbo/gloss/natlang should be split into 3 lines each. Compare to: http://dag.github.com/cll/7/6/#e10

pdf: needs fix
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: needs fix
mobi: needs fix

**Comment by rlpowell** [comment]
I chopped it up differently, but it looks much better now.
