### ISSUE TITLE
sudo ./run_docker.sh: ERROR

### ISSUE THREAD

**Issue by ghost** [lojban/cll#310]
Hi,

$ sudo ./run_docker.sh 2>> ERROR

If the first argument is '-v', then the following argument should be an extra directory to mount, for use with the ./cll_build -a or -A options, or 'none'.
Syntax is of docker's -v option, so to mount ~/www on /tmp/www, do: ~/www:/tmp/www

All other arguments are passed to ./cll_build

Sending build context to Docker daemon  452.6MB
Step 1/17 : FROM rlpowell/fedora_base
Docker build failed.
[ERROR.txt](https://github.com/lojban/cll/files/3245049/ERROR.txt)

**pull access denied for rlpowell/fedora_base, repository does not exist or may require 'docker login'**

**Comment by lagleki** [comment]
Still an issue?  Closing for now.
