### ISSUE TITLE
scripts/Makefile:53: recipe for target 'build/xhtml_chapter_chunks.done' failed

### ISSUE THREAD

**Issue by ghost** [lojban/cll#311]
Hi,

 ./cll_build -T all 1>>FILEOUT 2>>FILERROR

scripts/Makefile:53: recipe for target 'build/xhtml_chapter_chunks.done' failed

[FILEOUT.txt](https://github.com/lojban/cll/files/3245064/FILEOUT.txt)
[FILERROR.txt](https://github.com/lojban/cll/files/3245065/FILERROR.txt)

**Comment by lagleki** [comment]
Please, confirm if the issue still persists with the latest commits. Closing for now.
