### ISSUE TITLE
C9. Example 9.40 has the last two lines on one line

### ISSUE THREAD

**Issue by ento** [lojban/cll#35]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L45)

> Your watering the plant causes its growth. If you water the plant, then it grows.

Compare to: http://dag.github.com/cll/9/7/#e6

All formats affected.

**Comment by Ntsekees** [comment]
Fixed. Thanks!
