### ISSUE TITLE
C9. BAI tables at end of chapter are poorly formatted compared to the red book

### ISSUE THREAD

**Issue by ento** [lojban/cll#36]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L46)

pdf: needs fix
else: needs fix

**Comment by rlpowell** [comment]
I'm actually pretty happy with the formatting here (which has changed since this bug was opened); someone else can take this on if they want, but I'm going to leave it alone.

Please make a note here if you also think this is OK (or not), and if enough people do we can just close it.

**Comment by lagleki** [comment]
I suggest closing the issue.

**Comment by lagleki** [comment]
See http://lojban.org/publications/cll/cll_v1.1_xhtml-section-chunks/section-all-BAI.html

**Comment by lagleki** [comment]
Please reopen if needed
