### ISSUE TITLE
broken link in 4.2

### ISSUE THREAD

**Issue by nmtigor** [lojban/cll#366]
In chapter 4.2 "cmavo", the link "Chapter 20" is broken.

**Comment by lagleki** [comment]
Can you provide more information what you are looking at? E.g. http://lojban.org/publications/cll/cll_v1.1_xhtml-section-chunks/section-cmavo.html has the link working.

**Comment by nmtigor** [comment]
Fine. Because I was looking [here](http://lojban.github.io/cll/4/2/).

**Comment by lagleki** [comment]
So no problem? Should we close the issue?
