### ISSUE TITLE
Do we have CLL in other formats?

### ISSUE THREAD

**Issue by ksqsf** [lojban/cll#472]
Do we have CLL in other formats, like Markdown, rather than DocBook? I hope there's automatic building and deployment of an online version via CI like Github Actions, but DocBook makes that infeasible, as it takes too much time to build.

(Background: There was a translation project of CLL, but currently on halt, and IMHO the building time is partly responsible for that.)

I tried Pandoc but the results were not so good. It needs extra efforts to fix cross-chapter references, tables, example titles, etc. Hence I decided to ask here, maybe there is already one non-DocBook version I'm not aware of? :)

**Comment by lagleki** [comment]
On Wed, Jul 28, 2021, 12:26 ksqsf ***@***.***> wrote:

> Do we have CLL in other formats, like Markdown,
>

It's hard to convert from docbook to markdown. In most cases youd lose
indices. Why would you even want that? To translate it? You can just
convert html to docbook. Yes indices would be lost as well so manual work
of converting back to docbook would be necessary.

> rather than DocBook? I hope there's automatic building and deployment of
> an online version via CI like Github Actions, but DocBook makes that
> infeasible, as it takes too much time to build.
>

It's more about indices and the dictionary (compiling apoendices) rather
than docbook format.

(Background: There was a translation project of CLL, but currently on halt,
> and IMHO the building time is partly responsible for that.)
>

That is strange. Translation to Russian used to be smooth and only
knowledge of English and lojban led to difficulties.

**Comment by ksqsf** [comment]
Thanks for your quick reply! I've known the circumstances.

**Comment by rlpowell** [comment]
FWIW, anyone who wants to do CLL work is welcome to a shell account on one of my systems, where I can directly support build problems and also they're pretty beefy so a *complete* build takes maybe 30 minutes?

Also, using the -t flag with specific chapters makes builds *much* faster; a minute or two most of the time.
