### ISSUE TITLE
C16. After Example 16.93: plurals with spaces between the valsi and the "s"

### ISSUE THREAD

**Issue by ento** [lojban/cll#49]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L59)

CLL1.0 also has quotes around the valsi: http://dag.github.com/cll/16/11/

> Other expressions using two “naku”s may or may not cancel out. If there is no quantified variable between them, then the “naku”s cancel.

Could be a markup issue.

pdf: needs fix
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: needs fix
mobi: needs fix

**Comment by rlpowell** [comment]
Replaced "nakus" with "naku compounds" in each of 4 places.
