### ISSUE TITLE
C18. Section 24 is ridiculously tall

### ISSUE THREAD

**Issue by ento** [lojban/cll#56]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L66)

"Complete table of VUhU cmavo, with operand structures"

pdf: seems ok
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: needs fix
mobi: needs fix

**Comment by rlpowell** [comment]
Looks good to me.
