### ISSUE TITLE
The HTML and the LaTeX number the examples differently

### ISSUE THREAD

**Issue by ento** [lojban/cll#63]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L80)

Change this _AFTER_ handling all the proofread stuff, or it's going to suck.

---

From [L176 of the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L176):

> examples should be 5.2.1 rather than 5.6 for the first example in
>   section 2 of chapter 5

5.2.1 is the LaTeX-style numbering and 5.6 is how HTML is currently numbered.

**Comment by rlpowell** [comment]
No longer relevant with Prince.
