### ISSUE TITLE
Maybe add an interlinear-gloss-manual?

### ISSUE THREAD

**Issue by ento** [lojban/cll#64]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L88)

For manual grouping that isn't chapter 2 style; otherwise it's hard to see how to make something like this work:

```
le       se nelci      cu   cafne
The   liked-thing   is-frequent.
```

**Comment by rlpowell** [comment]
We went a different route for this by breaking up words and adding dashes and so on.
