### ISSUE TITLE
Check all the imported/manual indexterm entries for single words or selma'o

### ISSUE THREAD

**Issue by ento** [lojban/cll#67]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L106)

All the imported/manual indexterm entries for single words or selma'o need to be checked; they should be covered adequately by nearby `<cmavo-list>` or `<valsi>` entries, both of which create index entries.  If you don't know how to search for only the relevant entries in your particular text editor, ask here or on on #jbopre.

**Comment by rlpowell** [comment]
Can't find any anymore.
