### ISSUE TITLE
Clean up the "FIXME: TAG SPOT" bits

### ISSUE THREAD

**Issue by ento** [lojban/cll#68]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L114)

Those were put there as part of the semi-automated index insertion project.  If there's an `<indexterm>` next to them, great; kill it.  If there isn't, maybe look around nearby and make sure that obvious `<valsi>` tags and similar are in use.

**Comment by rlpowell** [comment]
All FIXMEs have already been dealt with before now.
