### ISSUE TITLE
Destroy entries like `<indexterm type="lojban-word-imported">` where appropriate

### ISSUE THREAD

**Issue by ento** [lojban/cll#69]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L122)

Similar to #68, entries like `<indexterm type="lojban-word">` (NOTE the type) probably need to be destroyed; there should be a bit of Lojban near them that can be wrapped in <valsi>, to exactly the same effect as the `<indexterm>` entry.  If you can't find such a correspondance, add an issue.

**Comment by rlpowell** [comment]
The perfect solution here is not obvious, but what I've just done is probably good enough.
