### ISSUE TITLE
Hunt down all FIXME:s and <!-- ... --> with todo type comments

### ISSUE THREAD

**Issue by ento** [lojban/cll#70]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L130)

---

[From L172 of the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L162):

> Fix all FIXMEs; in particular the output of:
> grep 'FIXME:' [0-9]*.xml | grep -v 'TAG SPOT'

**Comment by rlpowell** [comment]
Done.
