### ISSUE TITLE
Make sure the <interlinear-gloss> bits look right in the output

### ISSUE THREAD

**Issue by ento** [lojban/cll#71]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L143)

This is why the columns are so spaced out.

**Comment by rlpowell** [comment]
I feel like we've handled this pretty thoroughly in terms of the general behaviour of <interlinear-gloss>.  The details of each specific instance are what the chapter reviews are for.
