### ISSUE TITLE
Check for missing entries in the cmavo lists at the beginning of sections

### ISSUE THREAD

**Issue by ento** [lojban/cll#72]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L149)

> It seems that there is a problem with the cmavo lists at the beginning of sections having missing entries; in particular, ones with +/\* in the selma'o, maybe?; they need to be manually checked.

**Comment by rlpowell** [comment]
It really looks like this only applies to weird selma'o, so, here's all the relevant bits:

rlpowell@vrici> grep -P "^\t[a-z']+\t[A-Z][A-Z]" orig/catdoc.out | grep -v -P "^\t[a-z']+\t[A-Zh]+\t"
        na'ebo  NAhE+BO something other than
        to'ebo  NAhE+BO the opposite of
        no'ebo  NAhE+BO the neutral form of
        je'abo  NAhE+BO that which indeed is
        piro    PA+PA   the whole of/all of
        piso'a  PA+PA   almost the whole of
        piso'e  PA+PA   most of
        piso'i  PA+PA   much of
        piso'o  PA+PA   a small part of
        piso'u  PA+PA   a tiny part of
        pino'o  PA+PA   the typical portion of
        pirau   PA+PA   enough of
        pidu'e  PA+PA   too much of
        pimo'a  PA+PA   too little of
        boi     PA/BY   number or lerfu string
        do'u    COI/DOI vocative phrases
        ku      LE/LA   description sumti
        lu'u    LAhE/NAhE+BO    sumti qualifiers
        se'u    SEI/SOI metalinguistic insertions
rlpowell@vrici>

**Comment by rlpowell** [comment]
All now in place.
