### ISSUE TITLE
C18. Check for truncated math stuff and fix them

### ISSUE THREAD

**Issue by ento** [lojban/cll#76]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L159)

> there's a bunch of problems in 18.xml ; a lot of math stuff has
> gotten truncated in the final form.  they basically all need to be
> checked; having a CLL to hand would help

**Comment by rlpowell** [comment]
Spent a couple of hours in a coffee shop on this one.  :)
