### ISSUE TITLE
Links to examples should *say* "example N"

### ISSUE THREAD

**Issue by ento** [lojban/cll#78]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L173)

> links to examples should _say_ "example N"; easy to test from the
>   index

pdf: n/a | ok | needs fix | unconfirmed
html-nochunks: n/a | ok | needs fix | unconfirmed
html-chapters: n/a | ok | needs fix | unconfirmed
html-sections: n/a | ok | needs fix | unconfirmed
epub: n/a | ok | needs fix | unconfirmed
mobi: n/a | ok | needs fix | unconfirmed

**Comment by rlpowell** [comment]
Quote from current PDF:

In Example 1.15 (p. 6), John's coming has been anticipated by the speaker. In Example 1.13 (p. 6)
and Example 1.14 (p. 6), no such anticipation has been made, but in Example 1.14 (p. 6) the lack-ofanticipation
goes no further – in Example 1.13 (p. 6), it amounts to actual surprise

From HTML:

In Example 1.15, John's coming has been anticipated by the speaker. In Example 1.13 and Example 1.14, no such anticipation has been made, but in Example 1.14 the lack-of-anticipation goes no further – in Example 1.13, it amounts to actual surprise.
