### ISSUE TITLE
Links to sections should say the number of section and chapter

### ISSUE THREAD

**Issue by ento** [lojban/cll#79]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L175)

> links to sections should say the number of section and chapter

pdf: n/a | ok | needs fix | unconfirmed
html-nochunks: n/a | ok | needs fix | unconfirmed
html-chapters: n/a | ok | needs fix | unconfirmed
html-sections: n/a | ok | needs fix | unconfirmed
epub: n/a | ok | needs fix | unconfirmed
mobi: n/a | ok | needs fix | unconfirmed

**Comment by rlpowell** [comment]
PDF:
"To really understand these modifiers, try to use them in combination with one or two of the
attitudinals found in Section 13.2 (p. 313) and Section 13.3 (p. 316), and see what emotional pictures you
can build:"

HTML:

" In addition, there are a few cmavo that can act like brivla; these are mentioned in Section 1.1, and discussed in full in Chapter 1."
