### ISSUE TITLE
print: Add a header or footer to the left or the right page that has the number of the chapter you're in.

### ISSUE THREAD

**Issue by ento** [lojban/cll#80]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L178)

> print: Add a header or footer to the left or the right page that
>   has the number of the chapter you're in.

If we choose to do section-based indexing, they should also contain the section number the page is in.

**Comment by rlpowell** [comment]
One page side (not sure if it's recto or verso) now says things like: "6.4 Masses and sets"
