### ISSUE TITLE
Properly handle <cmavo-entry>s like the one for fu'i in chapter 13

### ISSUE THREAD

**Issue by ento** [lojban/cll#81]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L181)

> for chapter 13, needs code changes to handle things like this:

``` xml
      <cmavo-entry>
        <cmavo>fu'i</cmavo>
        <gismu>[frili]</gismu>
        <attitudinal-scale point="sai">with help</attitudinal-scale>
        <attitudinal-scale point="sai">easily</attitudinal-scale>
        <attitudinal-scale point="cu'i">without help</attitudinal-scale>
        <attitudinal-scale point="nai">with opposition</attitudinal-scale>
        <attitudinal-scale point="nai">with difficulty</attitudinal-scale>
      </cmavo-entry>
```

>  the way the red book does

Note: there's a chance that the issue title is not worded correctly. I'll correct it when I understand what needs to be done.

**Comment by rlpowell** [comment]
ga'i [galtu] hauteur; rank equal rank meekness; lack of rank
le'o aggressive passive defensive
vu'e [vrude] virtue (zabna) sin (mabla)

-- good enough for me (looks better in the actual PDF)
