### ISSUE TITLE
Generate more-readable anchors based on current section number and such

### ISSUE THREAD

**Issue by ento** [lojban/cll#83]
[Original line in the TODO file](https://github.com/dag/cll/blob/0d127150db8e4ba0dc059f8bf350a3dd30bc8f4e/TODO#L201)

> Similarily, generate more-readable anchors based on current
>   section number and such

pdf: n/a
html-nochunks: needs fix
html-chapters: needs fix
html-sections: needs fix
epub: n/a
mobi: n/a

**Comment by rlpowell** [comment]
It is not obvious to me what is wanted here?, but as of an upload I will shortly make all examples have a cXdYeZ anchor (chapter X section Y example Z) based on the old anchor scheme, which is pretty readable, and sections have cXsY and chapters have cX.

These really shouldn't be _used_, though, as if the examples or sections are moved around they will stop making sense; they are for backwards compatibility only.
