### ISSUE TITLE
C19. Example 19.3. should have a "wide space" between the topic and the comment

### ISSUE THREAD

**Issue by ento** [lojban/cll#90]
> zhe4 xiao1xi2 wo3 zhi1dao le
> this  news    I   know    [perfective]
> 
> The wide space in the first two versions of Example 19.3 separate the topic ( “this news”) from the comment ( “I know already”).

PDF: needs fix
All other: needs fix

**Comment by rlpowell** [comment]
Updated text to say "The colon" instead of "The wide space".
