### ISSUE TITLE
C13. Example 13.89. is missing all but a single word

### ISSUE THREAD

**Issue by ento** [lojban/cll#91]
From http://dag.github.com/cll/13/12/

> 12.7)  ru2guo3 ni3 kan4dao4 wo3 mei4mei, ni3 yi2ding4 zhi1dao4 ta1 huai2yun4 le
>        if you see-arrive my younger-sister, you certainly know she pregnant

All formats affected

**Comment by rlpowell** [comment]
Looks fine now.
