### ISSUE TITLE
C13 S4 attitudinal scale is shown vertically but the main body indicates it's horizontal

### ISSUE THREAD

**Issue by ento** [lojban/cll#92]
main body:

> three “positive” ones (shown below on the left), three “negative” ones (shown below on the right)

the scale:

> cai carmi
> sai tsali
> ru'e ruble
> cu'i cumki
> nairu'e
> naisai
> naicai

Also, the associated gismu should have square brackets around them.

Also, the PDF version shows the cmavo (up to cu'i) in italics.

All formats affected.

**Comment by rlpowell** [comment]
All fixed except the square brackets part, which I don't consider interesting/useful.
