### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by redchair123** [lojban/cll#99]
you know the drill

**Comment by nyarly** [comment]
Indeed, under what license is the CLL released? Standard copyright? CC?

Also, maybe a lost cause at this point but: a rights assignment may be in order.

**Comment by durka** [comment]
This should cover it, right? https://lojban.github.io/cll/1/8/ Hmm, maybe not all the scripts and code...

**Comment by audreytoskin** [comment]
I think the "Boring Legalities" subchapter should be sufficient. But it might be easier for people skimming the repository if that information was copied or linked from the README, or a LICENSE file.

**Comment by rlpowell** [comment]
Yes, there's a LICENSE file now.
